*----------------------------------------------------------------------*
*   INCLUDE DEMO_DYNPRO_MODIFY_SCREEN_SEL                              *
*----------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF SCREEN 1100.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME NO INTERVALS.
PARAMETERS: ACT AS CHECKBOX DEFAULT '1',
            INP AS CHECKBOX DEFAULT '1',
            OUT AS CHECKBOX DEFAULT '1',
            INV AS CHECKBOX DEFAULT '0'.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME NO INTERVALS.
PARAMETERS: REQ AS CHECKBOX DEFAULT '0',
            D3D AS CHECKBOX DEFAULT '1',
            HLP AS CHECKBOX DEFAULT '0',
            INT AS CHECKBOX DEFAULT '0'.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME NO INTERVALS.
PARAMETERS RQS AS CHECKBOX DEFAULT '0'.
SELECTION-SCREEN END OF BLOCK B3.

SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME NO INTERVALS.
PARAMETERS  LEN TYPE I DEFAULT 10.
SELECTION-SCREEN END OF BLOCK B4.

SELECTION-SCREEN END OF SCREEN 1100.
