REPORT pgl_system_field_on_ui.

SELECTION-SCREEN COMMENT /1(40) text-bad.
SELECTION-SCREEN uline /1(40).
PARAMETERS p_bad TYPE syst-langu.

SELECTION-SCREEN SKIP.

SELECTION-SCREEN COMMENT /1(40) text-god.
SELECTION-SCREEN uline /1(40).
PARAMETERS p_good TYPE pgl_langu.

SELECTION-SCREEN SKIP.
SELECTION-SCREEN COMMENT /1(40) text-txt.
